import "./globals.css";
import Navbar from "./components/Navbar";
import { Karla } from "next/font/google";

const karla = Karla({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={karla.className}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
